import {
  Button,
  Layout,
  Card,
  Checkbox,
  Switch,
  Drawer,
  Radio,
  Popconfirm,
  Spin,
  Popover,
  Menu,
  Dropdown,
  Avatar,
  Tabs,
  Form,
  Input,
  Progress,
  Select,
  Table,
  Divider,
  Modal,
  DatePicker,
  Pagination,
  Upload,
  Tag,
  Tree,
  Row,
  Col,
  Tooltip,
  List,
  TreeSelect,
  Space,
  Empty,
  Skeleton,
  TimePicker,
  Timeline,
  InputNumber,
  Slider 
} from "ant-design-vue";
import 'ant-design-vue/dist/antd.css';
export default function (app) {
  app.use(Button)
    .use(Timeline)
    .use(Layout)
    .use(Empty)
    .use(Drawer)
    .use(Radio)
    .use(Menu)
    .use(Form)
    .use(Input)
    .use(Spin)
    .use(Select)
    .use(Table)
    .use(Divider)
    .use(Modal)
    .use(DatePicker)
    .use(Pagination)
    .use(Upload)
    .use(Dropdown)
    .use(Progress)
    .use(Avatar)
    .use(Popconfirm)
    .use(Card)
    .use(Tag)
    .use(Popover)
    .use(Tabs)
    .use(Tree)
    .use(TreeSelect)
    .use(Switch)
    .use(Col)
    .use(Row)
    .use(Tooltip)
    .use(List)
    .use(Checkbox)
    .use(Space)
    .use(Skeleton)
    .use(InputNumber)
    .use(Slider)
    .use(TimePicker);
}
